pia-gprshelper: update to latest release
- improve default route handling when ethernet and ppp is used
- avoid creating a non character device file in setgprsapn when
  script is run while the GSM device is not powered

Signed-off-by: Björn Krombholz <b.krombholz@pironex.de>

diff --git a/recipes-pironex/pia-am335x/pia-gprshelper/setgprsapn b/recipes-pironex/pia-am335x/pia-gprshelper/setgprsapn
--- a/recipes-pironex/pia-am335x/pia-gprshelper/setgprsapn
+++ b/recipes-pironex/pia-am335x/pia-gprshelper/setgprsapn
@@ -9,6 +9,11 @@ else
   device="/dev/ttyUSB3"
 fi
 
+if [ ! -c $device ] ; then
+    echo "ERROR: $device is not a character file!"
+    exit 1
+fi
+
 $(chat -e TIMEOUT 2 "" "AT+CIMI" "OK" > "$device" < "$device" 2>/tmp/imsi)
 imsifile=$(cat /tmp/imsi)
 echo ImsiFile: "$imsifile"
